defaults: &defaults
  working_directory: /home/circleci/src/github.com/jwoffindin/terrafile
  docker:
    - image: cimg/go:1.20.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: build_and_test
          command: |
            go build -v
            go test -v

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
