# defaults: &defaults
#   working_directory: /home/circleci/src/github.com/jwoffindin/terrafile
#   docker:
#     - image: cimg/go:1.20.4

version: 2.1

orbs:
  gor: hubci/goreleaser@2.3.0

workflows:
  main:
    jobs:
      - build
      - gor/release:
          version: 1.7.0
          go-version: '1.20'
          dry-run: true

  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: 1.7.0
          go-version: '1.20'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: cimg/go:1.20.4
    steps:
      - checkout
      - run:
          name: build_and_test
          command: |
            make setup build test
